# Generated by Django 3.0.8 on 2020-11-28 11:11

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='collections/')),
                ('available', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kollekció',
                'verbose_name_plural': 'Kollekciók',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Ajándékkártya', max_length=200)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price_api_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Ajándékkártya',
                'verbose_name_plural': 'Ajándékkártyák',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(default='', max_length=2000)),
                ('sender', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Üzenet',
                'verbose_name_plural': 'Üzenetek',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('text', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Értesítés',
                'verbose_name_plural': 'Értesítések',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('size', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(blank=True, default=0)),
                ('studs', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'NORMAL'), (2, 'NICKEL_FREE'), (3, 'PLASTIC')], default=(1, 'NORMAL'), max_length=5)),
                ('available', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price_api_id', models.CharField(blank=True, default='', max_length=50)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Collection')),
            ],
            options={
                'verbose_name': 'Termék',
                'verbose_name_plural': 'Termékek',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Terméktípus',
                'verbose_name_plural': 'Terméktípusok',
                'ordering': ('color',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Kép',
                'verbose_name_plural': 'Képek',
                'ordering': ('product',),
            },
        ),
    ]
